os: osx
language: go

go:
- 1.12

before_install:
    - mkdir $HOME/src
    

install:
    - cd $HOME/src
    - git clone https://github.com/gohugoio/hugo.git
    - cd hugo
    - go install

before_script:
    - cd $TRAVIS_BUILD_DIR
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo
    - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: code  # branch contains Hugo generator code
    
notifications:
  slack: chensworkspace:0iUM9QJqC1dzq27bJ9Fw87pn