name: Deploy Blog Site
on:
  push:
    branches:
      - code

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: code

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        run: |
          npm install
          npm install hexo-cli -g
          npm install hexo-generator-index --save
          npm install hexo-generator-archive --save
          npm install hexo-generator-category --save
          npm install hexo-generator-tag --save
          npm install hexo-server --save
          npm install hexo-deployer-git --save


      - name: Delpoy
        run: |
          hexo clean
          hexo generate

          git config user.name "chen"
          git config user.email "hechen.dream@gmail.com"

          hexo deploy

  